// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbs3oxIEgmSBVdBP5mgVQ9fRiviqfV9ok',
    appId: '1:698513351953:web:a94bc0eda3be9e1df698b0',
    messagingSenderId: '698513351953',
    projectId: 'spark-77621',
    authDomain: 'spark-77621.firebaseapp.com',
    storageBucket: 'spark-77621.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpI_uCxwS11uvigzh3MozUZQ6e4B8syDM',
    appId: '1:698513351953:android:17a52f44ffe2c13af698b0',
    messagingSenderId: '698513351953',
    projectId: 'spark-77621',
    storageBucket: 'spark-77621.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDppX6HAEYWZv8tJnyCNXQT7sUxOQdIKHo',
    appId: '1:698513351953:ios:dc2c9de02f17964ef698b0',
    messagingSenderId: '698513351953',
    projectId: 'spark-77621',
    storageBucket: 'spark-77621.appspot.com',
    iosBundleId: 'com.example.spark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDppX6HAEYWZv8tJnyCNXQT7sUxOQdIKHo',
    appId: '1:698513351953:ios:dc2c9de02f17964ef698b0',
    messagingSenderId: '698513351953',
    projectId: 'spark-77621',
    storageBucket: 'spark-77621.appspot.com',
    iosBundleId: 'com.example.spark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbs3oxIEgmSBVdBP5mgVQ9fRiviqfV9ok',
    appId: '1:698513351953:web:98289b5fbe53c637f698b0',
    messagingSenderId: '698513351953',
    projectId: 'spark-77621',
    authDomain: 'spark-77621.firebaseapp.com',
    storageBucket: 'spark-77621.appspot.com',
  );
}
